### ISSUE TITLE
Feature request: 10.15 support

### ISSUE THREAD

**Issue by dgolteanu** [lysdexic-audio/OBSAudioRouter#2]
Hi, is there a timeline for Catalina support? Or MacOS 11 Big sure for that matter
Either would be useful for me
Thanks

**Comment by lysdexic-audio** [comment]
Hi Daniel,

I don’t have machine to test either of those OSs at this stage, perhaps when I upgrade.

Cheers

**Comment by dgolteanu** [comment]
Thanks for the update, I landed on your program while looking to get audio working for analogue video conversion over firewire from a Hi8 camcorder. Any suggestions for this?
Thanks again

**Comment by lysdexic-audio** [comment]
Hi Daniel,

Haven't tried analogue over firewire from Hi8 but I've seen USB devices
that do this
